version: '3.8'

services:
  db:
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data